language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.2"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - xz-utils
      - liblzma-dev
before_install:
  # Install node-gyp and node-pre-gyp so it is available for packaging and publishing
  - npm install node-gyp -g
  # Install coffee globally
  - npm install -g coffee-script
install:
  # We want to compile with g++ 4.8 when rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  # Ensure source install works and compiles correctly
  - npm install
  # test our module
  - npm test
  # Redo install and tests with multithread enabled
  # - ENABLE_MT=1 npm install
after_success:
